[windows] conditionally use C++11 portable sleep.
ros-visualization/interactive_markers pull request #63
Opened 2020-02-14 05:23 UTC by seanyen

On ROS 2 branches, the test uses `C++11`'s `<chrono>` and `<thread>` to implement the portable sleep. However, `Indigo-devel` targets `C++03` , in order not to break this assumption, I decided to conditionally use the `C++11` modern sleep only for the `C++11`-supported environment.

2020-02-14 05:25 UTC, seanyen commented
@tfoote @dgossow This is ready for review and merge. Thanks!

2020-02-14 13:53 UTC, stertingen commented
Both Ubuntu 14.04 and ROS Indigo are EOL. As far as I know, binary packages for Indigo are not updated any more, but maybe built from source. In that case, one can still disable tests or use the release version 1.11.4 when building.

So instead of adding this indirection, I'd suggest to assume that C++11 is available.

(As I'm not a maintainer, I shall not decide about this. It's just my opinion about this.)

2020-03-05 21:55 UTC, seanyen commented
@tfoote Friendly ping.

2020-03-16 08:00 UTC, dgossow requested changes
@seanyen I retargeted this against the (newly created) kinetic-devel branch. Please remove the conditionals and assume C++11 availability

2020-03-16 19:56 UTC, seanyen commented
@dgossow Thanks! I removed the conditional guard and assume the c++11 usage.

2020-03-20 18:06 UTC, seanyen commented
@dgossow This is ready for review and merge. Thanks!

2020-04-03 09:51 UTC, rhaschke approved these changes

2020-04-03 10:05 UTC, merged